#experiment_conifg.yaml
experiment_config:
  checkpoint_path: lightning_checkpoints
  run_name: null
  save_dir: ./mlruns

  seed: 123
  accelerator: gpu
  devices: auto
  precision: 32-true
  enable_progress_bar: true
  progress_refresh_rate: 10

  log_every_n_steps: 1
  check_eval_n_epoch: 1
  num_sanity_val_steps: 0
  check_metrics_n_epoch: 10