#iddpm2_config.yaml
model_name: MPtinyunet_iddpm
img_shape: [2, 3, 3]

network: 
  # in_channels: 2
  # time_emb_dim: 32
  # base_channels: 16
  # channel_mults: [1, 2, 2]
  # use_attention_at_level: [False, False, True]

  base_dim: 512
  depth: 3
  time_emb_dim: 64

loss_fn:
  u_buffer: None

sampler:
  num_steps: 100
  sigma_min: 0.002
  sigma_max: 80.0