experiment_config:
  experiment_name: null
  run_name: null
  save_dir: ./mlruns
  model_postfix: "sigbkg_MC_gauss_rank"

  seed: 123
  accelerator: gpu
  device: cuda
  devices: 1

  log_every_n_steps: 10
  check_eval_n_epoch: 1
  num_sanity_val_steps: 0
  check_metrics_n_epoch: 1