model_name: MPtinyunet_VE
img_shape: [2, 3, 3] #inchannels, w, h

network:
  # in_channels: 2
  # time_emb_dim: 32
  # base_channels: 32
  # channel_mults: [1, 2, 2]
  # use_attention_at_level: [False, False, True]

  base_dim: 128
  depth: 4
  time_emb_dim: 64

loss_fn:
  sigma_min: 0.02
  sigma_max: 100

sampler:
  num_steps: 70 #number of sampler steps
  sigma_min: 0.02
  sigma_max: 100
  S_churn: 80 #param for adding stohasticity 0=deterministic
  S_min: 0.05 #use det. steps at low noise levels
  S_max: 1 #where the det. path is turned into stohastic (det. sampling at high noise levels)
  S_noise: 1.007 #noise multiplier for gaussia

  solver: heun
